module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  testTimeout: 20000,
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  testPathIgnorePatterns: ['/node_modules/', '/dist/'],
  collectCoverage: true,
  collectCoverageFrom: [
    '**/*.{ts,tsx}',
    '!**/node_modules/**',
    '!**/__tests__/**',
    '!**/mocks/**',
    '!**/mock/**',
    '!**/migrations/**',
    '!**/database/migrations/**',
    '!**/interfaces/**',
    '!**/dto/**',
    '!**/dtos/**',
    '!**/entities/**',
    '!**/enum/**',
    '!**/enums/**',
    '!**/config/**',
    '!**/health/**',
    '!**/main.ts',
    '!**/app.module.ts',
    '!**/*.module.ts',
    '!**/*.entity.ts',
    '!**/*.dto.ts',
    '!**/*.interface.ts',
    '!**/*.enum.ts',
    '!**/*.config.ts',
    '!**/*.controller.ts',
    '!<rootDir>/main.ts',
    '!<rootDir>/app.module.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 80 ,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  preset: 'ts-jest',
};
