#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🚀 Running pre-push checks..."

# Build do projeto
echo "📦 Building project..."
yarn build

# Testes unitários
echo "🧪 Running unit tests..."
yarn test --passWithNoTests

echo "✅ Pre-push checks passed!"
